#!/bin/bash

NAME=FT
OUTPUT_PATH=./Exp/E-SwinV1-X/$NAME
mkdir -p $OUTPUT_PATH

# 16 128 768 6*6 target mask rate ((128/16)^2)/((768/16)^2) 0.278
# deepspeed mainSingle.py \
# deepspeed --hostfile=host mainSingle.py \
deepspeed --hostfile=hX mainX.py \
   --data_sample_input_path ./DATA/Merge/ \
   --data_padmask_input_path ./DATA/PadMask/ \
   --val_rate 0.1 \
   --pretrain_mask_rate 0.15 \
   --data_info ./data/DataInfo \
   --target_num_patches 4096 \
   --patch_per_var_side 64 \
   --model SwinV1 \
   --init_model unicornEarth-SwinV1-base \
   --train_stage FT \
   --ckpt_output_dir $OUTPUT_PATH \
   --data_output_path $OUTPUT_PATH \
   --seed 1017 \
   --per_device_train_batch_size 1 \
   --per_device_eval_batch_size 1 \
   --do_eval \
   --learning_rate 1e-4 \
   --weight_decay 0.1 \
   --num_train_epochs 1 \
   --gradient_accumulation_steps 1 \
   --lr_scheduler_type cosine \
   --num_warmup_steps 0 \
   --loss_l1_rate 1.0 \
   --loss_ms_ssim_rate 2.0 \
   --stats_path ./data/Stats/ \
   --target_var TCWV \
   --zero_stage 3 \
   # &> $OUTPUT_PATH/train.log
   